# Generated by Django 5.0.6 on 2024-05-13 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='creator_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
