# Generated by Django 5.0.6 on 2024-05-16 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_creator_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='question_uuid',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='quiz_uuid',
            new_name='quiz',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='creator_uuid',
            new_name='creator',
        ),
    ]
